<html><head><title>ATM</title>
<SCRIPT LANGUAGE= "VBSCRIPT">
function Clock()
dim h, m,s
h= hour(time())
m=minute(time())
s=second(time())
document.Clock.digit.Value=""&h&":"&m&":"&s
end function


function C_onmouseover
document.C.width=899
document.C.height=99
end function

function C_onmouseout
document.C.width=624
document.C.height=84
end function

function B_onmouseover
document.B.width=260
document.B.height=173
end function

function B_onmouseout
document.B.width=224
document.B.height=144
end function
function D_onmouseover
document.D.width=260
document.D.height=52
end function

function D_onmouseout
document.D.width=224
document.D.height=44
end function

function H_onmouseover
document.H.width=98
document.H.height=98
end function

function H_onmouseout
document.H.width=68
document.H.height=68
end function

</SCRIPT>

</head>
<body BGCOLOR="YELLOW" ><FONT COLOR=#ff##f SIZE"5">
START PROJECT</FONT>
</FONT>




</CENTER>
</BODY></HTML>